steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/spark/spark:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/spark/spark:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/spark/spark:$COMMIT_SHA
      - --region=${_REGION}
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --timeout=3600
      - --min-instances=1
      - --max-instances=1
      - --concurrency=80
      - --session-affinity
      - --set-env-vars=FIRESTORE_PROJECT_ID=$PROJECT_ID
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/spark/spark:$COMMIT_SHA
substitutions:
  _REGION: asia-east1
  _SERVICE: spark
